site_name: FastAPI SQLAlchemy Toolkit
site_url: https://e-kondr01.github.io/fastapi-sqlalchemy-toolkit/
repo_url: https://github.com/e-kondr01/fastapi-sqlalchemy-toolkit
repo_name: fastapi-sqlalchemy-toolkit

nav:
  - About: index.md
  - Usage: usage.md
  - Filters: filtering.md
  - Sorting: sorting.md
  - Transactions: transactions.md
  - Database Validation: db_validation.md
  - Extending: extension.md
  - Utilities: utils.md
  - Benefits: benefits.md

plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
        - locale: ru
          link: /ru/
          name: Русский
          nav:
            - Обзор: index.md
            - Использование: usage.md
            - Фильтрация: filtering.md
            - Сортировка: sorting.md
            - Транзакции: transactions.md
            - Валидация на уровне БД: db_validation.md
            - Расширение: extension.md
            - Утилиты: utils.md
            - Предпосылки: benefits.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - search.suggest
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - admonition
  - tables
