FROM python:3.12

WORKDIR /fastapi-sqlalchemy-toolkit

RUN pip install --upgrade pip
COPY ../../requirements.txt .
RUN pip install -r requirements.txt

COPY ../../.. .

ENTRYPOINT ["/bin/sh", "-c", "pytest"]
